features:
  timestamp:
    type: datetime
    format: '%Y-%m-%d %H:%M:%S'
    timeOfDay: 21
    weekend: 0
    dayOfWeek: 0
    holiday: 0
    season: 0
    encode: false
  demand:
    type: float
    size: 2048
    activeBits: 40
    numBuckets: 130
    minVal: 16530.842
    maxVal: 41946.077999999994
    seed: 42
  net_generation:
    type: float
    size: 2048
    activeBits: 40
    numBuckets: 130
    minVal: 7505.755000000001
    maxVal: 36376.90499999998
    seed: 46
  imbalance:
    type: float
    size: 2048
    activeBits: 40
    numBuckets: 130
    minVal: -1022.1729999999998
    maxVal: 15256.792999999996
    seed: 45
  imbalance_delta:
    type: float
    size: 2048
    activeBits: 40
    numBuckets: 130
    minVal: -2979.890999999999
    maxVal: 3611.110999999989
    seed: 43
  imbalance_residual:
    type: float
    size: 2048
    activeBits: 40
    numBuckets: 130
    minVal: -5814.732
    maxVal: 5600.892
    seed: 44
models:
  demand_model:
    sources:
    - demand
    features:
    - demand
  net_generation_model:
    sources:
    - net_generation
    features:
    - net_generation
  imbalance_model:
    sources:
    - imbalance
    features:
    - imbalance
  imbalance_delta_model:
    sources:
    - imbalance_delta
    features:
    - imbalance_delta
  imbalance_residual_model:
    sources:
    - imbalance_residual
    features:
    - imbalance_residual
data:
  timebase:
    mode: union
    on_missing: hold_last
  sources:
  - name: demand
    kind: csv
    unit: MW
    path: /Users/samheiserman/Desktop/repos/htm-monitor/data/grid/caiso_2019fit_2020_2022_pad0p00/demand.csv
    timestamp_col: timestamp
    timestamp_format: '%Y-%m-%d %H:%M:%S'
    fields:
      demand: value
    labels:
      event_windows:
      - name: outage_aug2020
        start: '2020-08-14 00:00:00'
        end: '2020-08-16 00:00:00'
      - name: outage_sept2022
        start: '2022-09-06 00:00:00'
        end: '2022-09-09 00:00:00'
  - name: net_generation
    kind: csv
    unit: MW
    path: /Users/samheiserman/Desktop/repos/htm-monitor/data/grid/caiso_2019fit_2020_2022_pad0p00/net_generation.csv
    timestamp_col: timestamp
    timestamp_format: '%Y-%m-%d %H:%M:%S'
    fields:
      net_generation: value
    labels:
      event_windows:
      - name: outage_aug2020
        start: '2020-08-14 00:00:00'
        end: '2020-08-16 00:00:00'
      - name: outage_sept2022
        start: '2022-09-06 00:00:00'
        end: '2022-09-09 00:00:00'
  - name: imbalance
    kind: csv
    unit: MW
    path: /Users/samheiserman/Desktop/repos/htm-monitor/data/grid/caiso_2019fit_2020_2022_pad0p00/imbalance.csv
    timestamp_col: timestamp
    timestamp_format: '%Y-%m-%d %H:%M:%S'
    fields:
      imbalance: value
    labels:
      event_windows:
      - name: outage_aug2020
        start: '2020-08-14 00:00:00'
        end: '2020-08-16 00:00:00'
      - name: outage_sept2022
        start: '2022-09-06 00:00:00'
        end: '2022-09-09 00:00:00'
  - name: imbalance_delta
    kind: csv
    unit: MW
    path: /Users/samheiserman/Desktop/repos/htm-monitor/data/grid/caiso_2019fit_2020_2022_pad0p00/imbalance_delta.csv
    timestamp_col: timestamp
    timestamp_format: '%Y-%m-%d %H:%M:%S'
    fields:
      imbalance_delta: value
    labels:
      event_windows:
      - name: outage_aug2020
        start: '2020-08-14 00:00:00'
        end: '2020-08-16 00:00:00'
      - name: outage_sept2022
        start: '2022-09-06 00:00:00'
        end: '2022-09-09 00:00:00'
  - name: imbalance_residual
    kind: csv
    unit: MW
    path: /Users/samheiserman/Desktop/repos/htm-monitor/data/grid/caiso_2019fit_2020_2022_pad0p00/imbalance_residual.csv
    timestamp_col: timestamp
    timestamp_format: '%Y-%m-%d %H:%M:%S'
    fields:
      imbalance_residual: value
    labels:
      event_windows:
      - name: outage_aug2020
        start: '2020-08-14 00:00:00'
        end: '2020-08-16 00:00:00'
      - name: outage_sept2022
        start: '2022-09-06 00:00:00'
        end: '2022-09-09 00:00:00'
run:
  warmup_steps: 1000
  learn_after_warmup: true
decision:
  score_key: anomaly_probability
  threshold: 0.99
  method: kofn_window
  k: 2
  window:
    size: 12
    per_model_hits: 5
  grouping:
    enabled: true
    k: 2
    min_consecutive_group_steps: 2
    min_alert_len: 6
    groups:
      gr_demand:
      - demand_model
      gr_generation:
      - net_generation_model
      gr_imbalance:
      - imbalance_model
      - imbalance_delta_model
      - imbalance_residual_model
plot:
  enable: true
  step_pause_s: 0.0001
  window: 1000
  show_ground_truth: true
  show_warmup_span: true
  max_label_len: 16
  model_label_colors:
    demand: tab:green
    net_generation: tab:red
    imbalance: tab:orange
    imbalance_delta: tab:orange
    imbalance_residual: tab:orange
